version: 2

sources:
  - name: public
    tables:
      - name: usuarios
      - name: categorias
      - name: productos
      - name: ordenes
      - name: detalleordenes
      - name: carrito
      - name: metodospago
      - name: ordenesmetodospago
      - name: reseñasproductos
      - name: historialpagos
      - name: direccionesenvio